import { CampaignConfig, Contribution, PublicCampaignData, Student } from './types';
import { calculatePublicAggregates } from './utils';

export const INITIAL_CAMPAIGN_CONFIG: CampaignConfig = {
  id: 'afamigos_fundraiser',
  title: 'Child Sponsorship Programme (CSP)',
  target: 25000,
  currencySymbol: '₹',
  active: true,
  createdAt: 1714500000000,
  updatedAt: 1714500000000,
};

const OFFICIAL_CLASS_NAMES: string[] = [
  'Aakanksh K S',
  'Abhimanyu Biswas Ruchi',
  'Abhinav Praveen',
  'Aditi Menon',
  'Alden Viviano Fernandes',
  'Alice Jose',
  'Aman Sajith',
  'Amreen Alam',
  'Anant Babbar',
  'Annamraju Sree Gnana Prasuna',
  'Antony Koshy K',
  'Anwesha Ahuja',
  'Ashith Kushal Reddy',
  'Aviral Agarwal',
  'B R Niveditha',
  'B V Sneha',
  'Bhavatharni T',
  'Bhawini Maheshwari',
  'Bijjala Chandaa Smaran',
  'Chirag P Patil',
  'Daivik Sharma',
  'Deeksha P N',
  'Deepshika K',
  'Dev Malkani',
  'Devitha A Patel',
  'Dhruv Krishnamurthy',
  'Divya P',
  'Divyanshi Singhal',
  'Gatik Apreja',
  'Gowri K Sajeev',
  'Gursheen Kaur Sandhu',
  'Hridhya Sudheer P',
  'Impana D K',
  'Jiya Ashish Mehta',
  'Jyoti Prabha Behera',
  'Jyotishko Das',
  'Khushi Holla',
  'Kiruthik M',
  'Kshathriyan Dhandayudhapani',
  'Kushalini A V',
  'L H Jeevithan',
  'Lakshay Arora',
  'Madhan R',
  'Mahima S',
  'Mansahib Singh Oberoi',
  'Mantasha Azim',
  'Manya Shroff',
  'N Skandesh Manikandan',
  'Parvathi Deepak',
  'Pavan Gowda V',
  'Prarthana R B',
  'Rachit Banthia',
  'Rajveer Singh Rajpal',
  'Rakshith Balaji',
  'Rama Krushna Panda',
  'Rohit Balaji S',
  'S B Sreshta',
  'Saarang Nallacherry',
  'Saksham Takiar',
  'Samarpan Sethi',
  'Sayan Mahanta',
  'Sejal Tulsyan',
  'Shlok Raghavendra',
  'Shruti G',
  'Shruti Priya Agrawal',
  'Shwetha R',
  'Sreehari Sudheer',
  'Swetha Raghunath',
  'Taani Jain',
  'Taanish Bahl',
  'Tejaswini B',
  'Thejas Ayyavu Saravanan',
  'Thoushiq Naresh',
  'Udit Khandelwal',
  'Vaishnavi Parthasarathy',
  'Vedansh Jain',
  'Vibha Tyagi',
  'Vishvashakshini K P',
  'Vivaan Vinod',
  'Yashvee Kedia',
];

// Generate 80 students sorted alphabetically with deterministic IDs
export const INITIAL_STUDENTS_ROSTER: Student[] = OFFICIAL_CLASS_NAMES.map((name, index) => {
  const idNum = String(index + 1).padStart(2, '0');
  return {
    id: `stu_${idNum}`,
    name,
    active: true,
    createdAt: 1714500000000 + index * 1000,
  };
});

// Production clean start: 0 initial contributions
export const INITIAL_CONTRIBUTIONS: Contribution[] = [];

export const INITIAL_PUBLIC_DATA: PublicCampaignData = calculatePublicAggregates(
  INITIAL_CAMPAIGN_CONFIG.target,
  INITIAL_CONTRIBUTIONS,
  INITIAL_STUDENTS_ROSTER
);
